from . import account_journal
from . import account_move
from . import account_tag
from . import jpk_account_tag
from . import jpk_document_type
from . import jpk_gtu
from . import jpk_tax_office
from . import product
from . import res_company
from . import res_partner
from . import xlsx_helper
